### ISSUE TITLE
[bug] POSITION_ORDER iterator is broken

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/client-python#106]
Hi,

```python
>>> for node in bblfsh.iterator(uasts[100], bblfsh.TreeOrder.POSITION_ORDER):
...     print(node)
... 
Segmentation fault (core dumped)
```

all other iterators are working well.

**Comment by juanjux** [comment]
![works](https://i.pinimg.com/originals/02/6c/7f/026c7f91e81734c8724b8ab725e3d1f1.jpg)

@EgorBu could you provide the code you're parsing to see if I can reproduce it?

**Comment by EgorBu** [comment]
The source code is in details of https://github.com/bblfsh/client-python/issues/108

**Comment by juanjux** [comment]
I still can't reproduce it. Please ensure you're using client-python 2.9.13 or (soon to be released) 2.9.14. Using this code myself:

```python
import bblfsh

client = bblfsh.BblfshClient("0.0.0.0:9432")
uast = client.parse('/home/juanjux/borrame/fixture_pos.py').uast
print(uast)

it = bblfsh.iterator(uast, bblfsh.TreeOrder.POSITION_ORDER)
for node in it:
    print(node.internal_type)
```

**Comment by juanjux** [comment]
Update to 2.9.14 and try again please.

**Comment by EgorBu** [comment]
Updated to 2.9.14 - and it works! Thanks, I think that this issue should be closed.

**Comment by juanjux** [comment]
Thanks @EgorBu, yep, we had some memory problems some versions ago.
