### ISSUE TITLE
The latest version is not found on pypi

### ISSUE THREAD

**Issue by smacker** [bblfsh/client-python#139]
I see there is version 2.12.7 in releases on github but when I try to install it:
```
Could not find a version that satisfies the requirement bblfsh<3.0,>=2.12.7 (from lookout-sdk==0.2.0) (from versions: 0.0.4, 0.0.5, 0.1.0, 0.2.0, 0.2.1, 0.2.3, 1.0.0, 1.0.1, 1.1.0, 2.0.0, 2.1.0, 2.2.1, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.1, 2.6.0, 2.6.1, 2.8.0, 2.8.1, 2.8.2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 2.9.6, 2.9.8, 2.9.10, 2.9.12, 2.9.13, 2.9.14, 2.10.0, 2.10.1, 2.11.0, 2.11.1, 2.11.2, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.12.5, 2.12.6)
```

Here https://pypi.org/search/?q=bblfsh I see only 2.12.6 too.

**Comment by juanjux** [comment]
Looks like `setup.py` was not updated with the version and thus the upload to pyi failed because it tried to re-do the previous one. I've updated setup.py and recreated the tag and uploaded to pypi.
