### ISSUE TITLE
failed to install on macos

### ISSUE THREAD

**Issue by gregkonushev-okta** [bblfsh/client-python#140]
I have installed `libxml2` from `brew`,
but `pip install bblfsh` fails with this error:
```
In file included from bblfsh/libuast/uast.cc:4:
bblfsh/libuast/uast_private.h:4:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^~~~~~~~~~~~~~~
1 error generated.
error: command 'g++' failed with exit status 1

```

**Comment by creachadair** [comment]
I believe libxml2 is keg-only, because Homebrew doesn't want to introduce link-time conflicts with existing system libraries. You may need to tell `pip` where the Homebrew include and lib paths are, though, perhaps something like:

```shell
CFLAGS="$(brew --prefix)/opt/libxml2/include" LDFLAGS="$(brew --prefix)/opt/libxml2/lib" pip install bblfsh
```

**Comment by juanjux** [comment]
Yes, as explained in the Dependencies section of the readme, this client depends on having libxml2 headers installed.

Next version will remove that requirement.

**Comment by creachadair** [comment]
> Yes, as explained in the Dependencies section of the readme, this client depends on having libxml2 headers installed.

I think the problem was that they _are_ installed, but Homebrew doesn't automatically link them to the default include path.

**Comment by gregkonushev-okta** [comment]
For Mojave MacOS I was able to solve this problem by installing command line tools from /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by bzz** [comment]
Thank you for reporting workaround @gregkonushev-okta 🎉

Will close this, if there no objections as a workaround is found AND a it's not worth documenting it elsewhere as @juanjux mentioned - a new version from #128 will not have this dependency at all.

**Comment by alichtman** [comment]
I just ran into this same issue, and the command that fixed the problem for me was: 

`env CFLAGS="-I$(brew --prefix)/opt/libxml2/include/libxml2" pip3 install bblfsh`

From @creachadair 

It would be helpful if this were added to the README.

**Comment by creachadair** [comment]
> I just ran into this same issue, and the command that fixed the problem for me was:
> 
> `env CFLAGS="-I$(brew --prefix)/opt/libxml2/include/libxml2" pip3 install bblfsh`
> 
> From @creachadair
> 
> It would be helpful if this were added to the README. I do not think #128 fixed this issue.

I believe #128 removes the dependency, but that the current release doesn't include it yet. We are planning to cut a release including these changes soon, and at that point this workaround should no longer be required. Sorry for the confusion about timing.

**Comment by bzz** [comment]
And [v3.0.0](https://github.com/bblfsh/client-python/releases/tag/v3.0.0) release is out now on pypi.
