### ISSUE TITLE
`raw` param is cited in docstring but doesn't appear in client.parse() signature

### ISSUE THREAD

**Issue by alichtman** [bblfsh/client-python#143]
https://github.com/bblfsh/client-python/blob/375fd7e7a1a74364a0b0ba38887bb87d39cf71c8/bblfsh/client.py#L71

```python
def parse(self, filename: str, language: Optional[str]=None, 
          contents: Optional[str]=None, mode: Optional[ModeType]=None, 
          timeout: Optional[int]=None) -> ResultContext:
```

**Comment by creachadair** [comment]
Thanks for pointing that out. I think we just forgot to clean that up after updating the function signature, I've sent #144 to clean it up.

**Comment by alichtman** [comment]
Got it, thanks for clearing that up!
