### ISSUE TITLE
Syntax for variable annotations requires  python 3.6=>

### ISSUE THREAD

**Issue by victorjof** [bblfsh/client-python#153]
https://github.com/bblfsh/client-python/blob/cc9fbc4cd52948cd23dea806c88af6381f0c84ce/bblfsh/node.py#L161

**Comment by creachadair** [comment]
@dennwc It seems to me we could just make Python ≥ 3.6 a requirement. Since we require Python 3 anyway, there doesn't appear to be much advantage to the older editions. What do you think?

**Comment by dennwc** [comment]
I don't know that much about Python ecosystem, but it sounds reasonable.
