### ISSUE TITLE
gRPC failure when running sample code

### ISSUE THREAD

**Issue by polemicducky** [bblfsh/client-python#160]
Hi,

Sorry, if this is not the proper forum for this. 

I'm trying to run the sample code on the readme but I'm getting some gRPC issues and a bit stuck on how to move forward. Hoping to get some help.

Running this piece of code 

```
    import bblfsh
    
    client = bblfsh.BblfshClient("0.0.0.0:9432")
    ctx = client.parse("/home/xxx/sampleBbl.py")
    print(ctx)
    resdict = ctx.get_all()
```

yields

```
    Traceback (most recent call last):
      File "/home/xxx/sampleBbl.py", line 4, in <module>
        ctx = client.parse("/home/xxx/sampleBbl.py")
      File "/home/xxx/.local/lib/python3.7/site-packages/bblfsh/client.py", line 84, in parse
        response = self._stub_v2.Parse(request, timeout=timeout)
      File "/home/xxx/.local/lib/python3.7/site-packages/grpc/_channel.py", line 565, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/home/xxx/.local/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
        raise _Rendezvous(state, None, None, deadline)
    grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
    	status = StatusCode.UNAVAILABLE
    	details = "failed to connect to all addresses"
    	debug_error_string = "{"created":"@1559792327.724273361","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3381,"referenced_errors":[{"created":"@1559792327.724266694","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":453,"grpc_status":14}]}"
```
    
I'm using python 3.7.1 on ubuntu 18.04.2 running on virtualbox. It's a corporate network, with proxy servers properly set up (able to download images from docker and packages from pip).

I've followed the instruction in https://docs.sourced.tech/babelfish/using-babelfish/getting-started closely, and deployment should be ok, as I'm able to run this code properly:

`docker exec -it bblfshd bblfshctl parse /opt/bblfsh/etc/examples/python.py`

Any tips would be appreciated, thank you!

**Comment by creachadair** [comment]
I don't know exactly what's going on here, but the error message appears to indicate a failure of the channel to connect to its target address. Assuming the Python code is running on the host, and given that `bblfshctl` is running inside the container, that suggests to me there is some problem with the mapping between the host port and the container port.

Is it possible your system has a firewall policy that interferes with the port mapping. Can you try running `lsof -i4tcp:9432` on the host and see if it is being listened? Assuming the `bblfsh` container is running with the appropriate exports, it should appear as bound on the host.

**Comment by polemicducky** [comment]
I tried `lsof -i4tcp:9432` and `lsof -i tcp:9432`, but both options are not displaying anything.

Not sure how it works exactly, but I was finally able to make it work by using `client = bblfsh.BblfshClient("localhost:9432")` instead of 0.0.0.0. 

Thanks for your support!

**Comment by creachadair** [comment]
> Not sure how it works exactly, but I was finally able to make it work by using `client = bblfsh.BblfshClient("localhost:9432")` instead of 0.0.0.0.

That's interesting. In principle 0.0.0.0 should have resolved to all the addresses bound by any interface. I suppose it's possible the network management software has done something to interfere with that resolution step. It might be worth seeing what `nslookup localhost` says.

**Comment by polemicducky** [comment]
Sorry for the late response, the output of that command is 
```
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	localhost
Address: 127.0.0.1
Name:	localhost
Address: ::1
```

**Comment by dennwc** [comment]
I think we should just change our examples to use `localhost` instead of `0.0.0.0` to prevent that kind of issues.
