### ISSUE TITLE
CPython: Node.kindOf does not distinguish NODE_UINT

### ISSUE THREAD

**Issue by bzz** [bblfsh/client-python#161]
While reading a native extension code, I noticed that [`Node.kindOf`](https://github.com/bblfsh/client-python/blob/788ceb12b22aa881542d44065137e1fc7e522fd5/bblfsh/pyuast.cc#L455) implementation does never return `NODE_UINT`, although this case seems to be handled in other places.

**Comment by dennwc** [comment]
Python doesn't have an unsigned integer type, so we have no real way for checking it.

We could define our custom unsigned integer type for this purpose, but I think this will be an overkill.

I'm closing this one, but feel free to reopen if you have any other concerns.
