### ISSUE TITLE
Adding filter examples to the README 

### ISSUE THREAD

**Issue by eiso** [bblfsh/client-python#25]
@juanjux thank you for the work on https://github.com/bblfsh/client-python/pull/23

Just opening an issue so that we add filter function (libuast) examples to the README because right now people will only discover it if they read the tests.

**Comment by juanjux** [comment]
Yes, I just wanted to get @manucorporat PR updated and fixed ASAP so we could work from that, I'll update the README  as soon as I fix https://github.com/bblfsh/client-python/issues/24

**Comment by abeaumont** [comment]
This is related to https://github.com/bblfsh/libuast/issues/20, `xpath` examples should be shared among the library and all the clients.

**Comment by juanjux** [comment]
@abeaumont definitely, just a couple commands in this project README showing what API to call and then it should link to that page see better examples of queries.

**Comment by eiso** [comment]
Agreed with @juanjux. It's just so that someone who lands on the repo can see how to use it and what function to call for it.

@mcuadros there should also probably be how to launch the server with the link to the documentation here, like you did for https://github.com/bblfsh/dashboard

**Comment by juanjux** [comment]
Fixed by #26
