### ISSUE TITLE
`pip install -U bblfsh` does not work for Python 2 

### ISSUE THREAD

**Issue by zurk** [bblfsh/client-python#27]
I get next output when run `pip install -U bblfsh`:
https://gist.github.com/zurk/c327a3923529aab58a246ef23deb148a

**Comment by juanjux** [comment]
Yes, looks like the CPython extension module doesn't compile with Python 2.7, I'll take a look.

**Comment by juanjux** [comment]
I've a version of the extension module that should work with both Python versions but noticed that the Python base code wasn't compatible with Python 2.7 anyway, so I'll keep it "Python 3 only" and we'll discuss if we want Python 2 compatibility later.
