### ISSUE TITLE
Does bblfsh.filter should return list (instead of iterator)?

### ISSUE THREAD

**Issue by zurk** [bblfsh/client-python#29]
It is a suggestion of enhancement. 
Sometimes I don't need a full list, and it is a more pythonic way to have an iterator instead of the list. 

To discuss.

**Comment by abeaumont** [comment]
I think it's a good idea and should be easy to implement.

**Comment by juanjux** [comment]
Agree.

**Comment by juanjux** [comment]
Fixed by #46.
