### ISSUE TITLE
ensure_docker_is_running() fails on macOS

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/client-python#5]
https://gist.github.com/marnovo/c88ae219e7a8787bd6a09d2396af6c5d

**Comment by vmarkovtsev** [comment]
Fixed by

* https://github.com/bblfsh/client-python/pull/11
* https://github.com/bblfsh/client-python/pull/12

cc/ @marnovo

**Comment by marnovo** [comment]
Merci!
