### ISSUE TITLE
Package install fails with "fatal error: memtracker.h: No such file or directory"

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/client-python#86]
E.g. https://travis-ci.org/src-d/ml/jobs/351095320#L2754

**Comment by juanjux** [comment]
Looks like `.h` files must be added to the MANIFEST file or Pypi doesn't load them. Should be fixed now in 2.9.4, sorry.

**Comment by vmarkovtsev** [comment]
Thanks for the quick fix!
