### ISSUE TITLE
Does this library work with python 2.7?

### ISSUE THREAD

**Issue by erizocosmico** [bblfsh/client-python#95]
Saw in travis.yml it's only tested in 3.6 and 3.7, but in PyPI is listed in the 2.7 category. Is it supported?

**Comment by juanjux** [comment]
No, it's Python 3 only, I'll take a look at the Pypi listing.

**Comment by juanjux** [comment]
Made the change in an already open PR to avoid versions messing so when it's merged and the version 2.9.10 is released it should not show on Pypi 2.7 category.
