### ISSUE TITLE
New grcpio causes conflict

### ISSUE THREAD

**Issue by r0mainK** [bblfsh/client-python#96]
In `requirements.txt`:

```
grpcio>=1.3,<=2.0
grpcio-tools>=1.3,<2.0
```

In `setup.py`:
```
 install_requires=[" install_requires=["grpcio==1.10.0", "grpcio-tools==1.10.0", "docker", "protobuf>=3.4.0"],==1.10.0", "grpcio-tools==1.10.0", "docker", "protobuf>=3.4.0"],
```

Now that version 1.11.0 of `grcpio` is out, this causes conflicts during coverage check for ml, among other things.

Could you either check that 1.11 is supported and change setup, or modify requirements to insure we use version 1.10 ?

**Comment by r0mainK** [comment]
Solved, thks @juanjux !
Closing.

**Comment by juanjux** [comment]
No problem! Usually, we wait for the PRs to be reviewed and merged before closing issues (it should auto-close once merged since it's linked with a "fixes" text), so I'll reopen.

**Comment by r0mainK** [comment]
My bad thought it was merged ^^okay gonna go check it out now !
