### ISSUE TITLE
[feature request] Add support to query supported languages (with installed drivers)

### ISSUE THREAD

**Issue by zurk** [bblfsh/client-python#98]
Similar to https://github.com/bblfsh/client-scala/issues/68 it is really useful to have this feature in Python client.
Now we (ML team) have a hardcoded list of languages:  https://github.com/src-d/ml/blob/master/sourced/ml/cmd_entries/args.py#L36-L40 and we should update it each time.

**Comment by smola** [comment]
Last agreement is that we don't expose it on clients, since it's already on the protobuf protocol.

**Comment by zurk** [comment]
@smola so I can get all supported languages from a protobuf message? Can not find anything in https://doc.bblf.sh/...

**Comment by bzz** [comment]
SDK has been updated and a new [bblfshd released](https://github.com/bblfsh/bblfshd/releases/tag/v2.5.0) so Python driver would need some ❤️  similar to https://github.com/bblfsh/client-go/pull/57 to expose `SupportedLanguages`
